'use client'
import React from 'react';
import { useEditor, EditorContent, BubbleMenu, FloatingMenu } from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import Image from '@tiptap/extension-image'
import Code from '@tiptap/extension-code';
import Placeholder from '@tiptap/extension-placeholder';

import CodeBlockLowlight from '@tiptap/extension-code-block-lowlight';
import { createLowlight, common } from 'lowlight';

import cn from 'classnames';


// import hljs from 'highlight.js';
import css from 'highlight.js/lib/languages/css';
import js from 'highlight.js/lib/languages/javascript';
import ts from 'highlight.js/lib/languages/typescript';
import html from 'highlight.js/lib/languages/xml';

import 'highlight.js/styles/atom-one-dark.css';

import Heading from '@tiptap/extension-heading';
import Document from '@tiptap/extension-document';
import Text from '@tiptap/extension-text';


import { IoMdCode } from "react-icons/io";
import { TbSourceCode, TbItalic, TbBold, TbStrikethrough } from "react-icons/tb";
import { FiList } from "react-icons/fi";
import { LuImagePlus } from "react-icons/lu";
import { CgFormatSeparator } from "react-icons/cg";
import { IoCloseOutline } from "react-icons/io5";
import { FaLink } from "react-icons/fa6";

const { title, content } = {
  "title": "<h1 class=\"content-header\">Setting the content</h1>",
  "content": "<blockquote><p><code>What is an .apk file?</code></p></blockquote><p>An Android Package Kit (APK) is the package file format used by the Android OS for distribution and installation of mobile apps. It is similar to the .exe file you have on Windows OS, a .apk file is for android.</p><p>Click <a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://google.com\">here</a> to navigate to google.com</p><h1><strong>Debug APK</strong></h1><h2><strong>What can I use it for?</strong></h2><p>A debug .apk file will allow you to install and test your app before publishing to app stores. Mind you, this is not yet ready for publishing, and there are quite a few things you’ll need to do to before you can publish. Nevertheless, it’ll be useful for initial distribution and testing.</p><p>You’ll need to enable debugging options on your phone to run this apk</p><ol><li><p>Download Music (up to 10,000 songs on a maximum of 5 devices under the same account)</p></li><li><p>Discover Music (the system will provide a tailored playlist generated by their algorithm)</p></li><li><p>Spotify Connect (provide a grant to play your music on different devices, you can use your mobile phone as a control for playing music on your PC under the same account)</p></li><li><p>Discover Friend Activities, what music they like (allows you to see what your friends you follow are listening to in real-time, and also will have friend recommendations in your search lists when connected to other social media apps like Facebook, Instagram, etc.)</p></li><li><p>Can share music with your friends through the other platform (Copy song links, embed code and Spotify URL, and share to your other social media apps)</p></li></ol><p></p><h2><strong>Prerequisite:</strong></h2><ul><li><p>react-native version &gt; 0.58</p></li><li><p>react-native version &gt; 0.58</p></li><li><p>react-native version &gt; 0.58</p></li></ul><h2><strong>How to generate one in 3 steps?</strong></h2><p><em>Step 1:</em> Go to the root of the project in the terminal and run the below command:</p><p>Place your terminal directory to <em>android</em> using:<br><code>cd android</code></p><p>For Windows,<br><code>gradlew assembleRelease</code></p><p>For Linux and Mac OSX:<br><code>./gradlew assembleRelease</code></p><p>ou will need a Java generated signing key which is a keystore file used to generate a React Native executable binary for Android. You can create one using the <em>keytool</em> in the terminal with the following command</p><p><code>keytool -genkey -v -keystore your_key_name.keystore -alias your_key_alias -keyalg RSA -keysize 2048 -validity 10000</code></p><p>Once you run the keytool utility, you’ll be prompted to type in a password.<br>*<em>Make sure you remember the password</em></p><pre><code class=\"hljs language-javascript\">signingConfigs { \n  release {\n    storeFile file('your_key_name.keystore')\n    storePassword System.console().readLine(\"\\nKeystorepassword:\")\n    keyAlias System.console().readLine(\"\\nAlias: \")\n    keyPassword System.console().readLine(\"\\nAlias password: \")\n  }\n}</code></pre><hr><p></p>"
}

const lowlight = createLowlight(common);
lowlight.register({
  js,
  ts,
  html,
  css
});

import hljs from 'highlight.js';
import BulletList from '@tiptap/extension-bullet-list';
import ListItem from '@tiptap/extension-list-item';
import OrderedList from '@tiptap/extension-ordered-list';
import useOnScreen from '@/hooks/useOnScreen';
import Link from '@tiptap/extension-link';

const Menu = ({ editor }) => {

  // const handleHeadingChange = (e) => {
  //   const handleHeadingChange = (e) => {
  //     if (!!e.target?.value) {
  //       editor.chain().focus().setHeading({ level: Number(e.target.value) }).run();
  //     } else {
  //       editor.chain().focus().unsetAllMarks();
  //     }

  //     // <select name='heading' className='w-fit text-slate-400' onChangeCapture={handleHeadingChange}>
  //     //       <option value="">Heading</option>
  //     //       <option
  //     //         className={editor.isActive('heading', { level: 1 } ? 'is-active text-slate-800' : '')}
  //     //         selected={editor.isActive('heading', { level: 1 })}
  //     //         value={1}>H1</option>
  //     //       <option
  //     //         className={editor.isActive('heading', { level: 2 } ? 'is-active text-slate-800' : '')}
  //     //         selected={editor.isActive('heading', { level: 2 })}
  //     //         value={2}>H2</option>
  //     //       <option
  //     //         className={editor.isActive('heading', { level: 3 } ? 'is-active text-slate-800' : 'no')}
  //     //         selected={editor.isActive('heading', { level: 3 })}
  //     //         value={3}>H3</option>
  //     //     </select>
  //   }
  // }

  const handleLinkAdd = () => {
    const url = window.prompt('URL');


    // cancelled
    if (url === null) return;

    if (!/^https?:\/\//.test(url)) return alert('Invalid url');

    editor.chain().focus().setLink({ href: url }).run();
  }

  const unsetLink = () => {
    editor.chain().focus().unsetLink().run();
  }

  return (
    <BubbleMenu className='editor-menu' editor={editor} tippyOptions={{ duration: 100 }}>
      <div className='flex gap-0'>
        {editor.can().setBold() && <button
          onClick={() => editor.chain().focus().toggleBold().run()}
          className={editor.isActive('bold') ? 'is-active' : ''}
        >
          <TbBold />
        </button>}
        {editor.can().setItalic() && <button
          onClick={() => editor.chain().focus().toggleItalic().run()}
          className={editor.isActive('italic') ? 'is-active' : ''}
        >
          <TbItalic />
        </button>}
        {editor.can().setStrike() && <button
          onClick={() => editor.chain().focus().toggleStrike().run()}
          className={editor.isActive('strike') ? 'is-active' : ''}
        >
          <TbStrikethrough />
        </button>}
      </div>
      <div className='flex gap-0'>
        <button onClick={() => editor.isActive('link') ? unsetLink() : handleLinkAdd()}
          className={editor.isActive('link') ? 'is-active' : ''}>
          <FaLink />
        </button>
      </div>
      <div className='flex gap-0'>
        <button onClick={() => editor.chain().focus().toggleBulletList().run()}
          className={editor.isActive('bulletList') ? 'is-active' : ''}>
          <FiList />
        </button>
        {editor.can().setCode() && <button
          onClick={() => editor.chain().focus().toggleCode().run()}
          className={editor.isActive('code') ? 'is-active' : ''}>
          <IoMdCode />
        </button>}
        <button
          onClick={() => editor.chain().focus().toggleCodeBlock({ language: 'javascript' }).run()}
          className={editor.isActive('codeBlock', {}) ? 'is-active' : ''}>
          <TbSourceCode />
        </button>
      </div>
      <div className='flex gap-1 font-semibold'>
        <button
          onClick={() => editor.chain().focus().toggleHeading({ level: 1 }).run()}
          className={editor.isActive('heading', { level: 1 }) ? 'is-active' : ''}
        >
          H1
        </button>
        <button
          onClick={() => editor.chain().focus().toggleHeading({ level: 2 }).run()}
          className={editor.isActive('heading', { level: 2 }) ? 'is-active' : ''}
        >
          H2
        </button>
        <button
          onClick={() => editor.chain().focus().toggleHeading({ level: 3 }).run()}
          className={editor.isActive('heading', { level: 3 }) ? 'is-active' : ''}
        >
          H3
        </button>
      </div>
    </BubbleMenu>
  );
}

const LeftMenu = ({ editor }) => {
  const [isOpen, setIsOpen] = React.useState(true);
  const containerRef = React.useRef();
  const isVisible = useOnScreen(containerRef)

  const handleSetSeparator = () => {
    editor.chain().focus().setHorizontalRule().run();
  }

  const addImage = React.useCallback(() => {
    const url = window.prompt('URL')
    if (url) editor.chain().focus().setImage({ src: url }).run();
  }, [editor]);

  const togglePlusClick = () => {
    setIsOpen(prev => !prev);
  }

  const addCloseIconCx = cn({
    'add-close-container': true,
    'rotate-45': !isOpen,
  });

  const close = (e) => {
    setIsOpen(false);
  }

  React.useEffect(() => {
    if (!isVisible) close();
  }, [isVisible]);

  return (
    <FloatingMenu editor={editor} tippyOptions={{ delay: 300, animateFill: true }}>
      <div ref={containerRef}>
        <div className="absolute bottom-0 translate-y-1/2 right-6 gap-2 flex text-slate-500 select-none">
          <div className="menu-actions-container">
            <div className={addCloseIconCx} onClick={togglePlusClick}>
              <IoCloseOutline size={28} />
            </div>
            {isOpen && (
              <div className="actions-container">
                <button><LuImagePlus onClick={addImage} size={20} /></button>
                <button><CgFormatSeparator onClick={handleSetSeparator} size={20} /></button>
              </div>
            )}
          </div>
        </div>
      </div>
    </FloatingMenu>
  );
}

const CustomDoc = Document.extend({
  content: 'heading',
  inline: true,
});

const BlogEditor = () => {
  const titleEditor = useEditor({
    content: title,
    extensions: [
      CustomDoc,
      Text,
      Heading.configure({ levels: [1], HTMLAttributes: { class: "content-header" } }),
      Placeholder.configure({
        placeholder: "Title...",
      }),
    ]
  });

  const editor = useEditor({
    content,
    extensions: [
      StarterKit.configure({
        heading: {
          levels: [1, 2, 3]
        }
      }),
      Image,
      Code,
      BulletList,
      OrderedList,
      ListItem,
      CodeBlockLowlight.configure({
        lowlight,
        languageClassPrefix: 'hljs language-',
        exitOnTripleEnter: true,
        exitOnArrowDown: true,
      }),
      Placeholder.configure({
        placeholder: ({ node }) => {
          if (node.type.name === 'heading') {
            return `Subheading ${node.attrs?.['level'] || ''}`;
          }
          return 'Your story here...';
        }
      }),
      Link.configure({
        autolink: false,
        linkOnPaste: true,
        openOnClick: false,
        // validate: href => /^https?:\/\//.test(href)
      })
    ]
  });

  const focusEditor = () => {
    if (editor) editor.commands.focus();
  }

  const handleTitleKeyDown = (e) => {
    if (e.key === "Enter") focusEditor();
  }

  const handleCopyClick = () => {
    if (!editor || !titleEditor) return;
    console.log({
      title: titleEditor.getHTML(),
      content: editor.getHTML()
    });
  }

  // React.useEffect(() => {
  //   hljs.highlightAll();
  // });

  return (
    <div className="w-full min-h-screen bg-white">
      {editor && <Menu editor={editor} />}
      {editor && <LeftMenu editor={editor} />}
      <div className='min-h-4 w-full flex flex-row items-center justify-center p-3'>
        <button className='rounded bg-blue-500 p-1 px-2 text-white' onClick={handleCopyClick}>Copy content</button>
      </div>
      <div className="w-full md:max-w-2xl mx-auto pt-10">
        <EditorContent id="heading" onKeyDown={handleTitleKeyDown} editor={titleEditor} />
        <EditorContent className="mt-10 mb-20" editor={editor} />
      </div>

      {/* <h3 className='ml-2'>getHTML and setInner</h3>
      <div className='m-2 border p-3 rounded-md border-slate-300'>
        <span dangerouslySetInnerHTML={{ __html: editor?.getHTML()  }}></span>
      </div> */}

      {/* <h3 className='ml-2'>Raw version</h3>
      <div className='m-2 border p-3 rounded-md border-slate-300'>
        <p>{editor?.getHTML()}</p>
      </div> */}
    </div>
  )
}

export default BlogEditor;
